#                                               -*- Autoconf -*-
# Process this file with autoconf to produce a configure script.

AC_PREREQ([2.69])
AC_INIT([gnucap-models],[0.0.0],[gnucap-devel@gnu.org])
AC_CONFIG_SRCDIR([plugins/models-ngspice17/mos1/mos1load.c])
AC_CONFIG_MACRO_DIR([m4])
AM_INIT_AUTOMAKE()
LT_INIT()

AC_CONFIG_FILES([Makefile])
AC_CONFIG_SUBDIRS([plugins/models-bsim
                   plugins/models-spice3f5])
AC_OUTPUT
