
TARGET = dio
$(TARGET):

include makedefs

HDRS = diodefs.h dioext.h dioitf.h wrapper.h

SPICE_VERSION = SPICE_3f

TESTS = d_diode.10 \
        d_diode.11a \
        d_diode.11b \
        d_diode.11c \
        d_diode.11 \
        d_diode.11d \
        d_diode.12 \
        d_diode.1 \
        d_diode.3 \
        d_diode.4  \
        d_diode.5 \
        d_diode.6 \
        d_diode.7 \
        d_diode.8 \
        d_diode.9 \
        d_diode.error1

# for now, only these...
TESTS = \
        d_diode.2 \
        d_diode.10 \
        d_diode.11 \
        d_diode.11a \
        d_diode.11b \
        d_diode.11c \
        d_diode.11d

include ../Make2
