
TARGET = bjt
$(TARGET):

include makedefs

HDRS = bjtdefs.h bjtext.h bjtitf.h wrapper.h

SPICE_VERSION = SPICE_3f

TESTS = d_bjt d_bjt.2 d_bjt-pnp \
        d_bjt-diffpair-ccs \
        d_bjt-diffpair-cjc \
        d_bjt-diffpair-nocap \
        d_bjt-diffpair-tr \
        d_bjt-diffpair-tr2 \
        d_bjt-diffpair-tran \
        d_bjt-rca3040 \
        d_bjt-schmitt-bypass \
        d_bjt-schmitt-nobypass

# almost. print command broken
# d_bjt-rtlinv

include ../Make2
